language: haskell

ghc:
  # - 7.10
  - 7.8
  - 7.6
  - 7.4

script:
  - cabal check && cabal update && cabal install --dependencies-only && cabal configure --enable-tests && cabal build -j --ghc-options=-Werror && cabal test && ./dist/build/hcopy/hcopy
